### your site title here 

#

title: Jeremiah Goddard
description: Robotics | Computer Vision | Machine Learning

baseurl: "/" # Needs to be empty for local development and 
url: "https://goddardjer.github.io" #custom url to be used instead of GitHub repository
email: goddarje@oregonstate.edu

repository: goddardjer/goddardjer.github.io # Add this line with your repository name


# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
email: "#"
linkedin: "#"
github: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
